//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Закупка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Закупка()
        {
            this.Состав_закупки = new HashSet<Состав_закупки>();
        }
    
        public int ID_закупки { get; set; }
        public Nullable<int> Общая_цена { get; set; }
        public Nullable<System.DateTime> Дата_закупки { get; set; }
        public Nullable<System.DateTime> Дата_поставки { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_закупки> Состав_закупки { get; set; }
    }
}
