//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Материал_объекта
    {
        public int ID_объекта { get; set; }
        public int ID_материала { get; set; }
        public string Единицы_измерения { get; set; }
        public Nullable<int> Количество_материала { get; set; }
    
        public virtual Материал Материал { get; set; }
        public virtual Объект Объект { get; set; }
    }
}
