//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Объект
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Объект()
        {
            this.Материал_объекта = new HashSet<Материал_объекта>();
            this.Работа_на_объекте = new HashSet<Работа_на_объекте>();
            this.Этап_выполнения = new HashSet<Этап_выполнения>();
        }
    
        public int ID_объекта { get; set; }
        public string Наименование_заказа { get; set; }
        public int ID_заказчика { get; set; }
        public Nullable<System.DateTime> Дата_принятия_заказа { get; set; }
        public string Срок_выполнения_работ { get; set; }
        public string Вид_работ { get; set; }
        public string Статус_заказа { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Материал_объекта> Материал_объекта { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Работа_на_объекте> Работа_на_объекте { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Этап_выполнения> Этап_выполнения { get; set; }
    }
}
