//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Состав_закупки
    {
        public int ID_закупки { get; set; }
        public int ID_материала { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<int> Цена { get; set; }
    
        public virtual Закупка Закупка { get; set; }
        public virtual Материал Материал { get; set; }
    }
}
