//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Этап_выполнения
    {
        public int ID_объекта { get; set; }
        public int ID_этапа { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Название___этапа { get; set; }
    
        public virtual Объект Объект { get; set; }
    }
}
